[project]
name = "nonebot-plugin-nailongremove-base"
dynamic = ["version"]
description = "识别目标并撤回图片插件"
authors = [
    { name = "445", email = "2877834692@qq.com" },
    { name = "student_2333", email = "lgc2333@126.com" },
]
requires-python = "<4.0,>=3.9"
dependencies = [
    "nonebot2>=2.2.0",
    "nonebot-plugin-alconna>=0.53.1",
    "nonebot-plugin-uninfo>=0.5.0",
    "opencv-python>=4.5",
    "numpy>=1.19",
    "keras>=2.4",
    "pillow>=9",
    "cookit[pydantic]>=0.8.1",
    "httpx>=0.27.2",
    "githubkit>=0.11.14",
    "yarl>=1.17.1",
    "tqdm>=4.66.6",
    "ultralytics>=8.0.0",  # 添加 ultralytics 依赖
]
license = { text = "MIT" }
readme = "README.md"
keywords = ["nonebot", "plugin", "image"]

[project.urls]
homepage = "https://github.com/Refound-445/nonebot-plugin-nailongremove"
repository = "https://github.com/Refound-445/nonebot-plugin-nailongremove"

[project.optional-dependencies]
model0 = [  # 保持原有的可选依赖组
    "tensorflow>=2.4",
]
model1 = [  # 更新目标检测模型依赖
    "ultralytics>=8.0.0",
    "torch>=2.0.0",  # ultralytics 需要 torch
]
hf = [  # 新增 HF API 的可选依赖组
    "gradio-client>=1.7.1",
]
all = [  # 更新 all 组，包含所有可选依赖
    "tensorflow>=2.4",
    "ultralytics>=8.0.0",
    "torch>=2.0.0",
    "gradio-client>=1.7.1",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = []

[tool.pdm.version]
source = "file"
path = "nonebot_plugin_nailongremove/__init__.py"